#pragma once

#if(CV_MAJOR_VERSION >= 3)
	#define CV_IMWRITE_JPEG_QUALITY IMWRITE_JPEG_QUALITY
	#define CV_CAP_PROP_FRAME_WIDTH CAP_PROP_FRAME_WIDTH
	#define CV_CAP_PROP_FRAME_HEIGHT CAP_PROP_FRAME_HEIGHT
	#define CV_CAP_PROP_FPS CAP_PROP_FPS
	#define CV_BGR2GRAY COLOR_BGR2GRAY
	#define CV_RETR_TREE RETR_TREE
	#define CV_CHAIN_APPROX_SIMPLE CHAIN_APPROX_SIMPLE
	#define CV_FOURCC VideoWriter::fourcc
#endif
